openapi: 3.0.3
info:
  title: Avitolog API Schema
  version: 1.0.0
  description: |
    API for Avitolog service. JWT via Authorization: Bearer <token>.
servers:
  - url: /api
paths:
  /auth/register/:
    post:
      summary: Register a new user and receive JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password]
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
              examples:
                ok:
                  value:
                    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                    user:
                      id: 1
                      username: demo
        '400':
          description: Bad Request
  /auth/login/:
    post:
      summary: Login with username/password and receive JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password]
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '400':
          description: Invalid credentials
  /auth/me/:
    get:
      summary: Get current user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPublic'
        '401':
          description: Unauthorized
  /listings/:
    get:
      summary: List listings
      parameters:
        - in: query
          name: ordering
          schema:
            type: string
            enum: ['-view_count', 'created_at', '-created_at']
          description: Ordering field
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
            minimum: 0
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Listing'
                  count:
                    type: integer
  /listings/resolve/:
    post:
      summary: Resolve listing by URL. Create if not exists, scraping og:title and og:image
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [url]
              properties:
                url:
                  type: string
      responses:
        '200':
          description: OK (existing)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listing'
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listing'
  /listings/{id}/:
    get:
      summary: Get listing by ID and increment view_count
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listing'
        '404':
          description: Not Found
  /listings/{id}/comments/:
    get:
      summary: Get approved comments for a listing
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
        - in: query
          name: ordering
          schema:
            type: string
            enum: ['-likes', '-created_at', 'created_at']
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Comment'
                  count:
                    type: integer
        '404':
          description: Listing Not Found
    post:
      summary: Create a comment for a listing (moderated)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [text]
              properties:
                text:
                  type: string
      responses:
        '201':
          description: Created (pending moderation)
          content:
            application/json:
              schema:
                type: object
                properties:
                  comment:
                    $ref: '#/components/schemas/Comment'
                  message:
                    type: string
              examples:
                created:
                  value:
                    comment:
                      id: 10
                      user:
                        id: 1
                        username: alice
                      text: Nice listing!
                      likes_count: 0
                      is_approved: false
                      created_at: '2025-01-01T12:00:00Z'
                    message: Comment submitted and pending moderation.
        '401':
          description: Unauthorized
        '404':
          description: Listing Not Found
  /comments/{id}/like/:
    post:
      summary: Toggle like for a comment
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  liked:
                    type: boolean
                  likes_count:
                    type: integer
        '401':
          description: Unauthorized
        '404':
          description: Comment Not Found
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UserPublic:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
    Listing:
      type: object
      properties:
        id:
          type: integer
        url:
          type: string
        title:
          type: string
        image_url:
          type: string
          nullable: true
        view_count:
          type: integer
        created_at:
          type: string
          format: date-time
    Comment:
      type: object
      properties:
        id:
          type: integer
        user:
          $ref: '#/components/schemas/UserPublic'
        text:
          type: string
        likes_count:
          type: integer
        is_approved:
          type: boolean
        created_at:
          type: string
          format: date-time
    Token:
      type: object
      properties:
        token:
          type: string
        user:
          $ref: '#/components/schemas/UserPublic'
